/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialNetworkAnalysisRouteImport } from './routes/social-network-analysis'
import { Route as RepositoryEvolutionRouteImport } from './routes/repository-evolution'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DeveloperAnalyticsRouteImport } from './routes/developer-analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CodebaseHealthRouteImport } from './routes/codebase-health'
import { Route as BusFactorAndOwnershipRouteImport } from './routes/bus-factor-and-ownership'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialNetworkAnalysisRepoPathRouteImport } from './routes/social-network-analysis.$repoPath'
import { Route as SocialNetworkAnalysisRepoIdRouteImport } from './routes/social-network-analysis.$repoId'
import { Route as RepositoryEvolutionRepoPathRouteImport } from './routes/repository-evolution.$repoPath'
import { Route as RepositoryEvolutionRepoIdRouteImport } from './routes/repository-evolution.$repoId'
import { Route as DeveloperAnalyticsRepoPathRouteImport } from './routes/developer-analytics.$repoPath'
import { Route as DeveloperAnalyticsRepoIdRouteImport } from './routes/developer-analytics.$repoId'
import { Route as DashboardRepoPathRouteImport } from './routes/dashboard.$repoPath'
import { Route as DashboardRepoIdRouteImport } from './routes/dashboard.$repoId'
import { Route as CrossRepoSocialNetworkAnalysisProjectIdRouteImport } from './routes/cross-repo-social-network-analysis.$projectId'
import { Route as CrossRepoRepositoryEvolutionProjectIdRouteImport } from './routes/cross-repo-repository-evolution.$projectId'
import { Route as CrossRepoCodebaseHealthProjectIdRouteImport } from './routes/cross-repo-codebase-health.$projectId'
import { Route as CrossRepoBusFactorAndOwnershipProjectIdRouteImport } from './routes/cross-repo-bus-factor-and-ownership.$projectId'
import { Route as CrossRepoAnalyticsProjectIdRouteImport } from './routes/cross-repo-analytics.$projectId'
import { Route as CodebaseHealthRepoPathRouteImport } from './routes/codebase-health.$repoPath'
import { Route as CodebaseHealthRepoIdRouteImport } from './routes/codebase-health.$repoId'
import { Route as BusFactorAndOwnershipRepoPathRouteImport } from './routes/bus-factor-and-ownership.$repoPath'
import { Route as BusFactorAndOwnershipRepoIdRouteImport } from './routes/bus-factor-and-ownership.$repoId'

const SocialNetworkAnalysisRoute = SocialNetworkAnalysisRouteImport.update({
  id: '/social-network-analysis',
  path: '/social-network-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryEvolutionRoute = RepositoryEvolutionRouteImport.update({
  id: '/repository-evolution',
  path: '/repository-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperAnalyticsRoute = DeveloperAnalyticsRouteImport.update({
  id: '/developer-analytics',
  path: '/developer-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseHealthRoute = CodebaseHealthRouteImport.update({
  id: '/codebase-health',
  path: '/codebase-health',
  getParentRoute: () => rootRouteImport,
} as any)
const BusFactorAndOwnershipRoute = BusFactorAndOwnershipRouteImport.update({
  id: '/bus-factor-and-ownership',
  path: '/bus-factor-and-ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialNetworkAnalysisRepoPathRoute =
  SocialNetworkAnalysisRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => SocialNetworkAnalysisRoute,
  } as any)
const SocialNetworkAnalysisRepoIdRoute =
  SocialNetworkAnalysisRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => SocialNetworkAnalysisRoute,
  } as any)
const RepositoryEvolutionRepoPathRoute =
  RepositoryEvolutionRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => RepositoryEvolutionRoute,
  } as any)
const RepositoryEvolutionRepoIdRoute =
  RepositoryEvolutionRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => RepositoryEvolutionRoute,
  } as any)
const DeveloperAnalyticsRepoPathRoute =
  DeveloperAnalyticsRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => DeveloperAnalyticsRoute,
  } as any)
const DeveloperAnalyticsRepoIdRoute =
  DeveloperAnalyticsRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => DeveloperAnalyticsRoute,
  } as any)
const DashboardRepoPathRoute = DashboardRepoPathRouteImport.update({
  id: '/$repoPath',
  path: '/$repoPath',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRepoIdRoute = DashboardRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => DashboardRoute,
} as any)
const CrossRepoSocialNetworkAnalysisProjectIdRoute =
  CrossRepoSocialNetworkAnalysisProjectIdRouteImport.update({
    id: '/cross-repo-social-network-analysis/$projectId',
    path: '/cross-repo-social-network-analysis/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoRepositoryEvolutionProjectIdRoute =
  CrossRepoRepositoryEvolutionProjectIdRouteImport.update({
    id: '/cross-repo-repository-evolution/$projectId',
    path: '/cross-repo-repository-evolution/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoCodebaseHealthProjectIdRoute =
  CrossRepoCodebaseHealthProjectIdRouteImport.update({
    id: '/cross-repo-codebase-health/$projectId',
    path: '/cross-repo-codebase-health/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoBusFactorAndOwnershipProjectIdRoute =
  CrossRepoBusFactorAndOwnershipProjectIdRouteImport.update({
    id: '/cross-repo-bus-factor-and-ownership/$projectId',
    path: '/cross-repo-bus-factor-and-ownership/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoAnalyticsProjectIdRoute =
  CrossRepoAnalyticsProjectIdRouteImport.update({
    id: '/cross-repo-analytics/$projectId',
    path: '/cross-repo-analytics/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CodebaseHealthRepoPathRoute = CodebaseHealthRepoPathRouteImport.update({
  id: '/$repoPath',
  path: '/$repoPath',
  getParentRoute: () => CodebaseHealthRoute,
} as any)
const CodebaseHealthRepoIdRoute = CodebaseHealthRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => CodebaseHealthRoute,
} as any)
const BusFactorAndOwnershipRepoPathRoute =
  BusFactorAndOwnershipRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => BusFactorAndOwnershipRoute,
  } as any)
const BusFactorAndOwnershipRepoIdRoute =
  BusFactorAndOwnershipRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => BusFactorAndOwnershipRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/social-network-analysis': typeof SocialNetworkAnalysisRouteWithChildren
  '/bus-factor-and-ownership/$repoId': typeof BusFactorAndOwnershipRepoIdRoute
  '/bus-factor-and-ownership/$repoPath': typeof BusFactorAndOwnershipRepoPathRoute
  '/codebase-health/$repoId': typeof CodebaseHealthRepoIdRoute
  '/codebase-health/$repoPath': typeof CodebaseHealthRepoPathRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/cross-repo-social-network-analysis/$projectId': typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  '/dashboard/$repoId': typeof DashboardRepoIdRoute
  '/dashboard/$repoPath': typeof DashboardRepoPathRoute
  '/developer-analytics/$repoId': typeof DeveloperAnalyticsRepoIdRoute
  '/developer-analytics/$repoPath': typeof DeveloperAnalyticsRepoPathRoute
  '/repository-evolution/$repoId': typeof RepositoryEvolutionRepoIdRoute
  '/repository-evolution/$repoPath': typeof RepositoryEvolutionRepoPathRoute
  '/social-network-analysis/$repoId': typeof SocialNetworkAnalysisRepoIdRoute
  '/social-network-analysis/$repoPath': typeof SocialNetworkAnalysisRepoPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/social-network-analysis': typeof SocialNetworkAnalysisRouteWithChildren
  '/bus-factor-and-ownership/$repoId': typeof BusFactorAndOwnershipRepoIdRoute
  '/bus-factor-and-ownership/$repoPath': typeof BusFactorAndOwnershipRepoPathRoute
  '/codebase-health/$repoId': typeof CodebaseHealthRepoIdRoute
  '/codebase-health/$repoPath': typeof CodebaseHealthRepoPathRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/cross-repo-social-network-analysis/$projectId': typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  '/dashboard/$repoId': typeof DashboardRepoIdRoute
  '/dashboard/$repoPath': typeof DashboardRepoPathRoute
  '/developer-analytics/$repoId': typeof DeveloperAnalyticsRepoIdRoute
  '/developer-analytics/$repoPath': typeof DeveloperAnalyticsRepoPathRoute
  '/repository-evolution/$repoId': typeof RepositoryEvolutionRepoIdRoute
  '/repository-evolution/$repoPath': typeof RepositoryEvolutionRepoPathRoute
  '/social-network-analysis/$repoId': typeof SocialNetworkAnalysisRepoIdRoute
  '/social-network-analysis/$repoPath': typeof SocialNetworkAnalysisRepoPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/social-network-analysis': typeof SocialNetworkAnalysisRouteWithChildren
  '/bus-factor-and-ownership/$repoId': typeof BusFactorAndOwnershipRepoIdRoute
  '/bus-factor-and-ownership/$repoPath': typeof BusFactorAndOwnershipRepoPathRoute
  '/codebase-health/$repoId': typeof CodebaseHealthRepoIdRoute
  '/codebase-health/$repoPath': typeof CodebaseHealthRepoPathRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/cross-repo-social-network-analysis/$projectId': typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  '/dashboard/$repoId': typeof DashboardRepoIdRoute
  '/dashboard/$repoPath': typeof DashboardRepoPathRoute
  '/developer-analytics/$repoId': typeof DeveloperAnalyticsRepoIdRoute
  '/developer-analytics/$repoPath': typeof DeveloperAnalyticsRepoPathRoute
  '/repository-evolution/$repoId': typeof RepositoryEvolutionRepoIdRoute
  '/repository-evolution/$repoPath': typeof RepositoryEvolutionRepoPathRoute
  '/social-network-analysis/$repoId': typeof SocialNetworkAnalysisRepoIdRoute
  '/social-network-analysis/$repoPath': typeof SocialNetworkAnalysisRepoPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/social-network-analysis'
    | '/bus-factor-and-ownership/$repoId'
    | '/bus-factor-and-ownership/$repoPath'
    | '/codebase-health/$repoId'
    | '/codebase-health/$repoPath'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/cross-repo-social-network-analysis/$projectId'
    | '/dashboard/$repoId'
    | '/dashboard/$repoPath'
    | '/developer-analytics/$repoId'
    | '/developer-analytics/$repoPath'
    | '/repository-evolution/$repoId'
    | '/repository-evolution/$repoPath'
    | '/social-network-analysis/$repoId'
    | '/social-network-analysis/$repoPath'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/social-network-analysis'
    | '/bus-factor-and-ownership/$repoId'
    | '/bus-factor-and-ownership/$repoPath'
    | '/codebase-health/$repoId'
    | '/codebase-health/$repoPath'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/cross-repo-social-network-analysis/$projectId'
    | '/dashboard/$repoId'
    | '/dashboard/$repoPath'
    | '/developer-analytics/$repoId'
    | '/developer-analytics/$repoPath'
    | '/repository-evolution/$repoId'
    | '/repository-evolution/$repoPath'
    | '/social-network-analysis/$repoId'
    | '/social-network-analysis/$repoPath'
  id:
    | '__root__'
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/social-network-analysis'
    | '/bus-factor-and-ownership/$repoId'
    | '/bus-factor-and-ownership/$repoPath'
    | '/codebase-health/$repoId'
    | '/codebase-health/$repoPath'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/cross-repo-social-network-analysis/$projectId'
    | '/dashboard/$repoId'
    | '/dashboard/$repoPath'
    | '/developer-analytics/$repoId'
    | '/developer-analytics/$repoPath'
    | '/repository-evolution/$repoId'
    | '/repository-evolution/$repoPath'
    | '/social-network-analysis/$repoId'
    | '/social-network-analysis/$repoPath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusFactorAndOwnershipRoute: typeof BusFactorAndOwnershipRouteWithChildren
  CodebaseHealthRoute: typeof CodebaseHealthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DeveloperAnalyticsRoute: typeof DeveloperAnalyticsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RepositoryEvolutionRoute: typeof RepositoryEvolutionRouteWithChildren
  SocialNetworkAnalysisRoute: typeof SocialNetworkAnalysisRouteWithChildren
  CrossRepoAnalyticsProjectIdRoute: typeof CrossRepoAnalyticsProjectIdRoute
  CrossRepoBusFactorAndOwnershipProjectIdRoute: typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  CrossRepoCodebaseHealthProjectIdRoute: typeof CrossRepoCodebaseHealthProjectIdRoute
  CrossRepoRepositoryEvolutionProjectIdRoute: typeof CrossRepoRepositoryEvolutionProjectIdRoute
  CrossRepoSocialNetworkAnalysisProjectIdRoute: typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-network-analysis': {
      id: '/social-network-analysis'
      path: '/social-network-analysis'
      fullPath: '/social-network-analysis'
      preLoaderRoute: typeof SocialNetworkAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-evolution': {
      id: '/repository-evolution'
      path: '/repository-evolution'
      fullPath: '/repository-evolution'
      preLoaderRoute: typeof RepositoryEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-analytics': {
      id: '/developer-analytics'
      path: '/developer-analytics'
      fullPath: '/developer-analytics'
      preLoaderRoute: typeof DeveloperAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase-health': {
      id: '/codebase-health'
      path: '/codebase-health'
      fullPath: '/codebase-health'
      preLoaderRoute: typeof CodebaseHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-factor-and-ownership': {
      id: '/bus-factor-and-ownership'
      path: '/bus-factor-and-ownership'
      fullPath: '/bus-factor-and-ownership'
      preLoaderRoute: typeof BusFactorAndOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-network-analysis/$repoPath': {
      id: '/social-network-analysis/$repoPath'
      path: '/$repoPath'
      fullPath: '/social-network-analysis/$repoPath'
      preLoaderRoute: typeof SocialNetworkAnalysisRepoPathRouteImport
      parentRoute: typeof SocialNetworkAnalysisRoute
    }
    '/social-network-analysis/$repoId': {
      id: '/social-network-analysis/$repoId'
      path: '/$repoId'
      fullPath: '/social-network-analysis/$repoId'
      preLoaderRoute: typeof SocialNetworkAnalysisRepoIdRouteImport
      parentRoute: typeof SocialNetworkAnalysisRoute
    }
    '/repository-evolution/$repoPath': {
      id: '/repository-evolution/$repoPath'
      path: '/$repoPath'
      fullPath: '/repository-evolution/$repoPath'
      preLoaderRoute: typeof RepositoryEvolutionRepoPathRouteImport
      parentRoute: typeof RepositoryEvolutionRoute
    }
    '/repository-evolution/$repoId': {
      id: '/repository-evolution/$repoId'
      path: '/$repoId'
      fullPath: '/repository-evolution/$repoId'
      preLoaderRoute: typeof RepositoryEvolutionRepoIdRouteImport
      parentRoute: typeof RepositoryEvolutionRoute
    }
    '/developer-analytics/$repoPath': {
      id: '/developer-analytics/$repoPath'
      path: '/$repoPath'
      fullPath: '/developer-analytics/$repoPath'
      preLoaderRoute: typeof DeveloperAnalyticsRepoPathRouteImport
      parentRoute: typeof DeveloperAnalyticsRoute
    }
    '/developer-analytics/$repoId': {
      id: '/developer-analytics/$repoId'
      path: '/$repoId'
      fullPath: '/developer-analytics/$repoId'
      preLoaderRoute: typeof DeveloperAnalyticsRepoIdRouteImport
      parentRoute: typeof DeveloperAnalyticsRoute
    }
    '/dashboard/$repoPath': {
      id: '/dashboard/$repoPath'
      path: '/$repoPath'
      fullPath: '/dashboard/$repoPath'
      preLoaderRoute: typeof DashboardRepoPathRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$repoId': {
      id: '/dashboard/$repoId'
      path: '/$repoId'
      fullPath: '/dashboard/$repoId'
      preLoaderRoute: typeof DashboardRepoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cross-repo-social-network-analysis/$projectId': {
      id: '/cross-repo-social-network-analysis/$projectId'
      path: '/cross-repo-social-network-analysis/$projectId'
      fullPath: '/cross-repo-social-network-analysis/$projectId'
      preLoaderRoute: typeof CrossRepoSocialNetworkAnalysisProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-repository-evolution/$projectId': {
      id: '/cross-repo-repository-evolution/$projectId'
      path: '/cross-repo-repository-evolution/$projectId'
      fullPath: '/cross-repo-repository-evolution/$projectId'
      preLoaderRoute: typeof CrossRepoRepositoryEvolutionProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-codebase-health/$projectId': {
      id: '/cross-repo-codebase-health/$projectId'
      path: '/cross-repo-codebase-health/$projectId'
      fullPath: '/cross-repo-codebase-health/$projectId'
      preLoaderRoute: typeof CrossRepoCodebaseHealthProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-bus-factor-and-ownership/$projectId': {
      id: '/cross-repo-bus-factor-and-ownership/$projectId'
      path: '/cross-repo-bus-factor-and-ownership/$projectId'
      fullPath: '/cross-repo-bus-factor-and-ownership/$projectId'
      preLoaderRoute: typeof CrossRepoBusFactorAndOwnershipProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-analytics/$projectId': {
      id: '/cross-repo-analytics/$projectId'
      path: '/cross-repo-analytics/$projectId'
      fullPath: '/cross-repo-analytics/$projectId'
      preLoaderRoute: typeof CrossRepoAnalyticsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase-health/$repoPath': {
      id: '/codebase-health/$repoPath'
      path: '/$repoPath'
      fullPath: '/codebase-health/$repoPath'
      preLoaderRoute: typeof CodebaseHealthRepoPathRouteImport
      parentRoute: typeof CodebaseHealthRoute
    }
    '/codebase-health/$repoId': {
      id: '/codebase-health/$repoId'
      path: '/$repoId'
      fullPath: '/codebase-health/$repoId'
      preLoaderRoute: typeof CodebaseHealthRepoIdRouteImport
      parentRoute: typeof CodebaseHealthRoute
    }
    '/bus-factor-and-ownership/$repoPath': {
      id: '/bus-factor-and-ownership/$repoPath'
      path: '/$repoPath'
      fullPath: '/bus-factor-and-ownership/$repoPath'
      preLoaderRoute: typeof BusFactorAndOwnershipRepoPathRouteImport
      parentRoute: typeof BusFactorAndOwnershipRoute
    }
    '/bus-factor-and-ownership/$repoId': {
      id: '/bus-factor-and-ownership/$repoId'
      path: '/$repoId'
      fullPath: '/bus-factor-and-ownership/$repoId'
      preLoaderRoute: typeof BusFactorAndOwnershipRepoIdRouteImport
      parentRoute: typeof BusFactorAndOwnershipRoute
    }
  }
}

interface BusFactorAndOwnershipRouteChildren {
  BusFactorAndOwnershipRepoIdRoute: typeof BusFactorAndOwnershipRepoIdRoute
  BusFactorAndOwnershipRepoPathRoute: typeof BusFactorAndOwnershipRepoPathRoute
}

const BusFactorAndOwnershipRouteChildren: BusFactorAndOwnershipRouteChildren = {
  BusFactorAndOwnershipRepoIdRoute: BusFactorAndOwnershipRepoIdRoute,
  BusFactorAndOwnershipRepoPathRoute: BusFactorAndOwnershipRepoPathRoute,
}

const BusFactorAndOwnershipRouteWithChildren =
  BusFactorAndOwnershipRoute._addFileChildren(
    BusFactorAndOwnershipRouteChildren,
  )

interface CodebaseHealthRouteChildren {
  CodebaseHealthRepoIdRoute: typeof CodebaseHealthRepoIdRoute
  CodebaseHealthRepoPathRoute: typeof CodebaseHealthRepoPathRoute
}

const CodebaseHealthRouteChildren: CodebaseHealthRouteChildren = {
  CodebaseHealthRepoIdRoute: CodebaseHealthRepoIdRoute,
  CodebaseHealthRepoPathRoute: CodebaseHealthRepoPathRoute,
}

const CodebaseHealthRouteWithChildren = CodebaseHealthRoute._addFileChildren(
  CodebaseHealthRouteChildren,
)

interface DashboardRouteChildren {
  DashboardRepoIdRoute: typeof DashboardRepoIdRoute
  DashboardRepoPathRoute: typeof DashboardRepoPathRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRepoIdRoute: DashboardRepoIdRoute,
  DashboardRepoPathRoute: DashboardRepoPathRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeveloperAnalyticsRouteChildren {
  DeveloperAnalyticsRepoIdRoute: typeof DeveloperAnalyticsRepoIdRoute
  DeveloperAnalyticsRepoPathRoute: typeof DeveloperAnalyticsRepoPathRoute
}

const DeveloperAnalyticsRouteChildren: DeveloperAnalyticsRouteChildren = {
  DeveloperAnalyticsRepoIdRoute: DeveloperAnalyticsRepoIdRoute,
  DeveloperAnalyticsRepoPathRoute: DeveloperAnalyticsRepoPathRoute,
}

const DeveloperAnalyticsRouteWithChildren =
  DeveloperAnalyticsRoute._addFileChildren(DeveloperAnalyticsRouteChildren)

interface RepositoryEvolutionRouteChildren {
  RepositoryEvolutionRepoIdRoute: typeof RepositoryEvolutionRepoIdRoute
  RepositoryEvolutionRepoPathRoute: typeof RepositoryEvolutionRepoPathRoute
}

const RepositoryEvolutionRouteChildren: RepositoryEvolutionRouteChildren = {
  RepositoryEvolutionRepoIdRoute: RepositoryEvolutionRepoIdRoute,
  RepositoryEvolutionRepoPathRoute: RepositoryEvolutionRepoPathRoute,
}

const RepositoryEvolutionRouteWithChildren =
  RepositoryEvolutionRoute._addFileChildren(RepositoryEvolutionRouteChildren)

interface SocialNetworkAnalysisRouteChildren {
  SocialNetworkAnalysisRepoIdRoute: typeof SocialNetworkAnalysisRepoIdRoute
  SocialNetworkAnalysisRepoPathRoute: typeof SocialNetworkAnalysisRepoPathRoute
}

const SocialNetworkAnalysisRouteChildren: SocialNetworkAnalysisRouteChildren = {
  SocialNetworkAnalysisRepoIdRoute: SocialNetworkAnalysisRepoIdRoute,
  SocialNetworkAnalysisRepoPathRoute: SocialNetworkAnalysisRepoPathRoute,
}

const SocialNetworkAnalysisRouteWithChildren =
  SocialNetworkAnalysisRoute._addFileChildren(
    SocialNetworkAnalysisRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusFactorAndOwnershipRoute: BusFactorAndOwnershipRouteWithChildren,
  CodebaseHealthRoute: CodebaseHealthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DeveloperAnalyticsRoute: DeveloperAnalyticsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RepositoryEvolutionRoute: RepositoryEvolutionRouteWithChildren,
  SocialNetworkAnalysisRoute: SocialNetworkAnalysisRouteWithChildren,
  CrossRepoAnalyticsProjectIdRoute: CrossRepoAnalyticsProjectIdRoute,
  CrossRepoBusFactorAndOwnershipProjectIdRoute:
    CrossRepoBusFactorAndOwnershipProjectIdRoute,
  CrossRepoCodebaseHealthProjectIdRoute: CrossRepoCodebaseHealthProjectIdRoute,
  CrossRepoRepositoryEvolutionProjectIdRoute:
    CrossRepoRepositoryEvolutionProjectIdRoute,
  CrossRepoSocialNetworkAnalysisProjectIdRoute:
    CrossRepoSocialNetworkAnalysisProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
