/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoryEvolutionRouteImport } from './routes/repository-evolution'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DeveloperAnalyticsRouteImport } from './routes/developer-analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CodebaseHealthRouteImport } from './routes/codebase-health'
import { Route as BusFactorAndOwnershipRouteImport } from './routes/bus-factor-and-ownership'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoryEvolutionRepoPathRouteImport } from './routes/repository-evolution.$repoPath'
import { Route as DeveloperAnalyticsRepoPathRouteImport } from './routes/developer-analytics.$repoPath'
import { Route as DashboardRepoPathRouteImport } from './routes/dashboard.$repoPath'
import { Route as CrossRepoRepositoryEvolutionProjectIdRouteImport } from './routes/cross-repo-repository-evolution.$projectId'
import { Route as CrossRepoCodebaseHealthProjectIdRouteImport } from './routes/cross-repo-codebase-health.$projectId'
import { Route as CrossRepoBusFactorAndOwnershipProjectIdRouteImport } from './routes/cross-repo-bus-factor-and-ownership.$projectId'
import { Route as CrossRepoAnalyticsProjectIdRouteImport } from './routes/cross-repo-analytics.$projectId'
import { Route as CodebaseHealthRepoPathRouteImport } from './routes/codebase-health.$repoPath'
import { Route as BusFactorAndOwnershipRepoPathRouteImport } from './routes/bus-factor-and-ownership.$repoPath'

const RepositoryEvolutionRoute = RepositoryEvolutionRouteImport.update({
  id: '/repository-evolution',
  path: '/repository-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperAnalyticsRoute = DeveloperAnalyticsRouteImport.update({
  id: '/developer-analytics',
  path: '/developer-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseHealthRoute = CodebaseHealthRouteImport.update({
  id: '/codebase-health',
  path: '/codebase-health',
  getParentRoute: () => rootRouteImport,
} as any)
const BusFactorAndOwnershipRoute = BusFactorAndOwnershipRouteImport.update({
  id: '/bus-factor-and-ownership',
  path: '/bus-factor-and-ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryEvolutionRepoPathRoute =
  RepositoryEvolutionRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => RepositoryEvolutionRoute,
  } as any)
const DeveloperAnalyticsRepoPathRoute =
  DeveloperAnalyticsRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => DeveloperAnalyticsRoute,
  } as any)
const DashboardRepoPathRoute = DashboardRepoPathRouteImport.update({
  id: '/$repoPath',
  path: '/$repoPath',
  getParentRoute: () => DashboardRoute,
} as any)
const CrossRepoRepositoryEvolutionProjectIdRoute =
  CrossRepoRepositoryEvolutionProjectIdRouteImport.update({
    id: '/cross-repo-repository-evolution/$projectId',
    path: '/cross-repo-repository-evolution/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoCodebaseHealthProjectIdRoute =
  CrossRepoCodebaseHealthProjectIdRouteImport.update({
    id: '/cross-repo-codebase-health/$projectId',
    path: '/cross-repo-codebase-health/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoBusFactorAndOwnershipProjectIdRoute =
  CrossRepoBusFactorAndOwnershipProjectIdRouteImport.update({
    id: '/cross-repo-bus-factor-and-ownership/$projectId',
    path: '/cross-repo-bus-factor-and-ownership/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoAnalyticsProjectIdRoute =
  CrossRepoAnalyticsProjectIdRouteImport.update({
    id: '/cross-repo-analytics/$projectId',
    path: '/cross-repo-analytics/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CodebaseHealthRepoPathRoute = CodebaseHealthRepoPathRouteImport.update({
  id: '/$repoPath',
  path: '/$repoPath',
  getParentRoute: () => CodebaseHealthRoute,
} as any)
const BusFactorAndOwnershipRepoPathRoute =
  BusFactorAndOwnershipRepoPathRouteImport.update({
    id: '/$repoPath',
    path: '/$repoPath',
    getParentRoute: () => BusFactorAndOwnershipRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/bus-factor-and-ownership/$repoPath': typeof BusFactorAndOwnershipRepoPathRoute
  '/codebase-health/$repoPath': typeof CodebaseHealthRepoPathRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/dashboard/$repoPath': typeof DashboardRepoPathRoute
  '/developer-analytics/$repoPath': typeof DeveloperAnalyticsRepoPathRoute
  '/repository-evolution/$repoPath': typeof RepositoryEvolutionRepoPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/bus-factor-and-ownership/$repoPath': typeof BusFactorAndOwnershipRepoPathRoute
  '/codebase-health/$repoPath': typeof CodebaseHealthRepoPathRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/dashboard/$repoPath': typeof DashboardRepoPathRoute
  '/developer-analytics/$repoPath': typeof DeveloperAnalyticsRepoPathRoute
  '/repository-evolution/$repoPath': typeof RepositoryEvolutionRepoPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/bus-factor-and-ownership/$repoPath': typeof BusFactorAndOwnershipRepoPathRoute
  '/codebase-health/$repoPath': typeof CodebaseHealthRepoPathRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/dashboard/$repoPath': typeof DashboardRepoPathRoute
  '/developer-analytics/$repoPath': typeof DeveloperAnalyticsRepoPathRoute
  '/repository-evolution/$repoPath': typeof RepositoryEvolutionRepoPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/bus-factor-and-ownership/$repoPath'
    | '/codebase-health/$repoPath'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/dashboard/$repoPath'
    | '/developer-analytics/$repoPath'
    | '/repository-evolution/$repoPath'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/bus-factor-and-ownership/$repoPath'
    | '/codebase-health/$repoPath'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/dashboard/$repoPath'
    | '/developer-analytics/$repoPath'
    | '/repository-evolution/$repoPath'
  id:
    | '__root__'
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/bus-factor-and-ownership/$repoPath'
    | '/codebase-health/$repoPath'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/dashboard/$repoPath'
    | '/developer-analytics/$repoPath'
    | '/repository-evolution/$repoPath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusFactorAndOwnershipRoute: typeof BusFactorAndOwnershipRouteWithChildren
  CodebaseHealthRoute: typeof CodebaseHealthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DeveloperAnalyticsRoute: typeof DeveloperAnalyticsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RepositoryEvolutionRoute: typeof RepositoryEvolutionRouteWithChildren
  CrossRepoAnalyticsProjectIdRoute: typeof CrossRepoAnalyticsProjectIdRoute
  CrossRepoBusFactorAndOwnershipProjectIdRoute: typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  CrossRepoCodebaseHealthProjectIdRoute: typeof CrossRepoCodebaseHealthProjectIdRoute
  CrossRepoRepositoryEvolutionProjectIdRoute: typeof CrossRepoRepositoryEvolutionProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repository-evolution': {
      id: '/repository-evolution'
      path: '/repository-evolution'
      fullPath: '/repository-evolution'
      preLoaderRoute: typeof RepositoryEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-analytics': {
      id: '/developer-analytics'
      path: '/developer-analytics'
      fullPath: '/developer-analytics'
      preLoaderRoute: typeof DeveloperAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase-health': {
      id: '/codebase-health'
      path: '/codebase-health'
      fullPath: '/codebase-health'
      preLoaderRoute: typeof CodebaseHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-factor-and-ownership': {
      id: '/bus-factor-and-ownership'
      path: '/bus-factor-and-ownership'
      fullPath: '/bus-factor-and-ownership'
      preLoaderRoute: typeof BusFactorAndOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-evolution/$repoPath': {
      id: '/repository-evolution/$repoPath'
      path: '/$repoPath'
      fullPath: '/repository-evolution/$repoPath'
      preLoaderRoute: typeof RepositoryEvolutionRepoPathRouteImport
      parentRoute: typeof RepositoryEvolutionRoute
    }
    '/developer-analytics/$repoPath': {
      id: '/developer-analytics/$repoPath'
      path: '/$repoPath'
      fullPath: '/developer-analytics/$repoPath'
      preLoaderRoute: typeof DeveloperAnalyticsRepoPathRouteImport
      parentRoute: typeof DeveloperAnalyticsRoute
    }
    '/dashboard/$repoPath': {
      id: '/dashboard/$repoPath'
      path: '/$repoPath'
      fullPath: '/dashboard/$repoPath'
      preLoaderRoute: typeof DashboardRepoPathRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cross-repo-repository-evolution/$projectId': {
      id: '/cross-repo-repository-evolution/$projectId'
      path: '/cross-repo-repository-evolution/$projectId'
      fullPath: '/cross-repo-repository-evolution/$projectId'
      preLoaderRoute: typeof CrossRepoRepositoryEvolutionProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-codebase-health/$projectId': {
      id: '/cross-repo-codebase-health/$projectId'
      path: '/cross-repo-codebase-health/$projectId'
      fullPath: '/cross-repo-codebase-health/$projectId'
      preLoaderRoute: typeof CrossRepoCodebaseHealthProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-bus-factor-and-ownership/$projectId': {
      id: '/cross-repo-bus-factor-and-ownership/$projectId'
      path: '/cross-repo-bus-factor-and-ownership/$projectId'
      fullPath: '/cross-repo-bus-factor-and-ownership/$projectId'
      preLoaderRoute: typeof CrossRepoBusFactorAndOwnershipProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-analytics/$projectId': {
      id: '/cross-repo-analytics/$projectId'
      path: '/cross-repo-analytics/$projectId'
      fullPath: '/cross-repo-analytics/$projectId'
      preLoaderRoute: typeof CrossRepoAnalyticsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase-health/$repoPath': {
      id: '/codebase-health/$repoPath'
      path: '/$repoPath'
      fullPath: '/codebase-health/$repoPath'
      preLoaderRoute: typeof CodebaseHealthRepoPathRouteImport
      parentRoute: typeof CodebaseHealthRoute
    }
    '/bus-factor-and-ownership/$repoPath': {
      id: '/bus-factor-and-ownership/$repoPath'
      path: '/$repoPath'
      fullPath: '/bus-factor-and-ownership/$repoPath'
      preLoaderRoute: typeof BusFactorAndOwnershipRepoPathRouteImport
      parentRoute: typeof BusFactorAndOwnershipRoute
    }
  }
}

interface BusFactorAndOwnershipRouteChildren {
  BusFactorAndOwnershipRepoPathRoute: typeof BusFactorAndOwnershipRepoPathRoute
}

const BusFactorAndOwnershipRouteChildren: BusFactorAndOwnershipRouteChildren = {
  BusFactorAndOwnershipRepoPathRoute: BusFactorAndOwnershipRepoPathRoute,
}

const BusFactorAndOwnershipRouteWithChildren =
  BusFactorAndOwnershipRoute._addFileChildren(
    BusFactorAndOwnershipRouteChildren,
  )

interface CodebaseHealthRouteChildren {
  CodebaseHealthRepoPathRoute: typeof CodebaseHealthRepoPathRoute
}

const CodebaseHealthRouteChildren: CodebaseHealthRouteChildren = {
  CodebaseHealthRepoPathRoute: CodebaseHealthRepoPathRoute,
}

const CodebaseHealthRouteWithChildren = CodebaseHealthRoute._addFileChildren(
  CodebaseHealthRouteChildren,
)

interface DashboardRouteChildren {
  DashboardRepoPathRoute: typeof DashboardRepoPathRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRepoPathRoute: DashboardRepoPathRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeveloperAnalyticsRouteChildren {
  DeveloperAnalyticsRepoPathRoute: typeof DeveloperAnalyticsRepoPathRoute
}

const DeveloperAnalyticsRouteChildren: DeveloperAnalyticsRouteChildren = {
  DeveloperAnalyticsRepoPathRoute: DeveloperAnalyticsRepoPathRoute,
}

const DeveloperAnalyticsRouteWithChildren =
  DeveloperAnalyticsRoute._addFileChildren(DeveloperAnalyticsRouteChildren)

interface RepositoryEvolutionRouteChildren {
  RepositoryEvolutionRepoPathRoute: typeof RepositoryEvolutionRepoPathRoute
}

const RepositoryEvolutionRouteChildren: RepositoryEvolutionRouteChildren = {
  RepositoryEvolutionRepoPathRoute: RepositoryEvolutionRepoPathRoute,
}

const RepositoryEvolutionRouteWithChildren =
  RepositoryEvolutionRoute._addFileChildren(RepositoryEvolutionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusFactorAndOwnershipRoute: BusFactorAndOwnershipRouteWithChildren,
  CodebaseHealthRoute: CodebaseHealthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DeveloperAnalyticsRoute: DeveloperAnalyticsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RepositoryEvolutionRoute: RepositoryEvolutionRouteWithChildren,
  CrossRepoAnalyticsProjectIdRoute: CrossRepoAnalyticsProjectIdRoute,
  CrossRepoBusFactorAndOwnershipProjectIdRoute:
    CrossRepoBusFactorAndOwnershipProjectIdRoute,
  CrossRepoCodebaseHealthProjectIdRoute: CrossRepoCodebaseHealthProjectIdRoute,
  CrossRepoRepositoryEvolutionProjectIdRoute:
    CrossRepoRepositoryEvolutionProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
