/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalDebtIndicatorsRouteImport } from './routes/technical-debt-indicators'
import { Route as SocialNetworkAnalysisRouteImport } from './routes/social-network-analysis'
import { Route as RiskAnalyticsRouteImport } from './routes/risk-analytics'
import { Route as RepositoryEvolutionRouteImport } from './routes/repository-evolution'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DeveloperAnalyticsRouteImport } from './routes/developer-analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CodebaseHealthRouteImport } from './routes/codebase-health'
import { Route as BusFactorAndOwnershipRouteImport } from './routes/bus-factor-and-ownership'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicalDebtIndicatorsRepoIdRouteImport } from './routes/technical-debt-indicators.$repoId'
import { Route as SocialNetworkAnalysisRepoIdRouteImport } from './routes/social-network-analysis.$repoId'
import { Route as RiskAnalyticsRepoIdRouteImport } from './routes/risk-analytics.$repoId'
import { Route as RepositoryEvolutionRepoIdRouteImport } from './routes/repository-evolution.$repoId'
import { Route as DeveloperAnalyticsRepoIdRouteImport } from './routes/developer-analytics.$repoId'
import { Route as DashboardRepoIdRouteImport } from './routes/dashboard.$repoId'
import { Route as CrossRepoTechnicalDebtIndicatorsProjectIdRouteImport } from './routes/cross-repo-technical-debt-indicators.$projectId'
import { Route as CrossRepoSocialNetworkAnalysisProjectIdRouteImport } from './routes/cross-repo-social-network-analysis.$projectId'
import { Route as CrossRepoRiskAnalyticsProjectIdRouteImport } from './routes/cross-repo-risk-analytics.$projectId'
import { Route as CrossRepoRepositoryEvolutionProjectIdRouteImport } from './routes/cross-repo-repository-evolution.$projectId'
import { Route as CrossRepoCodebaseHealthProjectIdRouteImport } from './routes/cross-repo-codebase-health.$projectId'
import { Route as CrossRepoBusFactorAndOwnershipProjectIdRouteImport } from './routes/cross-repo-bus-factor-and-ownership.$projectId'
import { Route as CrossRepoAnalyticsProjectIdRouteImport } from './routes/cross-repo-analytics.$projectId'
import { Route as CodebaseHealthRepoIdRouteImport } from './routes/codebase-health.$repoId'
import { Route as BusFactorAndOwnershipRepoIdRouteImport } from './routes/bus-factor-and-ownership.$repoId'

const TechnicalDebtIndicatorsRoute = TechnicalDebtIndicatorsRouteImport.update({
  id: '/technical-debt-indicators',
  path: '/technical-debt-indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialNetworkAnalysisRoute = SocialNetworkAnalysisRouteImport.update({
  id: '/social-network-analysis',
  path: '/social-network-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAnalyticsRoute = RiskAnalyticsRouteImport.update({
  id: '/risk-analytics',
  path: '/risk-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryEvolutionRoute = RepositoryEvolutionRouteImport.update({
  id: '/repository-evolution',
  path: '/repository-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperAnalyticsRoute = DeveloperAnalyticsRouteImport.update({
  id: '/developer-analytics',
  path: '/developer-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseHealthRoute = CodebaseHealthRouteImport.update({
  id: '/codebase-health',
  path: '/codebase-health',
  getParentRoute: () => rootRouteImport,
} as any)
const BusFactorAndOwnershipRoute = BusFactorAndOwnershipRouteImport.update({
  id: '/bus-factor-and-ownership',
  path: '/bus-factor-and-ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalDebtIndicatorsRepoIdRoute =
  TechnicalDebtIndicatorsRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => TechnicalDebtIndicatorsRoute,
  } as any)
const SocialNetworkAnalysisRepoIdRoute =
  SocialNetworkAnalysisRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => SocialNetworkAnalysisRoute,
  } as any)
const RiskAnalyticsRepoIdRoute = RiskAnalyticsRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => RiskAnalyticsRoute,
} as any)
const RepositoryEvolutionRepoIdRoute =
  RepositoryEvolutionRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => RepositoryEvolutionRoute,
  } as any)
const DeveloperAnalyticsRepoIdRoute =
  DeveloperAnalyticsRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => DeveloperAnalyticsRoute,
  } as any)
const DashboardRepoIdRoute = DashboardRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => DashboardRoute,
} as any)
const CrossRepoTechnicalDebtIndicatorsProjectIdRoute =
  CrossRepoTechnicalDebtIndicatorsProjectIdRouteImport.update({
    id: '/cross-repo-technical-debt-indicators/$projectId',
    path: '/cross-repo-technical-debt-indicators/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoSocialNetworkAnalysisProjectIdRoute =
  CrossRepoSocialNetworkAnalysisProjectIdRouteImport.update({
    id: '/cross-repo-social-network-analysis/$projectId',
    path: '/cross-repo-social-network-analysis/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoRiskAnalyticsProjectIdRoute =
  CrossRepoRiskAnalyticsProjectIdRouteImport.update({
    id: '/cross-repo-risk-analytics/$projectId',
    path: '/cross-repo-risk-analytics/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoRepositoryEvolutionProjectIdRoute =
  CrossRepoRepositoryEvolutionProjectIdRouteImport.update({
    id: '/cross-repo-repository-evolution/$projectId',
    path: '/cross-repo-repository-evolution/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoCodebaseHealthProjectIdRoute =
  CrossRepoCodebaseHealthProjectIdRouteImport.update({
    id: '/cross-repo-codebase-health/$projectId',
    path: '/cross-repo-codebase-health/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoBusFactorAndOwnershipProjectIdRoute =
  CrossRepoBusFactorAndOwnershipProjectIdRouteImport.update({
    id: '/cross-repo-bus-factor-and-ownership/$projectId',
    path: '/cross-repo-bus-factor-and-ownership/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrossRepoAnalyticsProjectIdRoute =
  CrossRepoAnalyticsProjectIdRouteImport.update({
    id: '/cross-repo-analytics/$projectId',
    path: '/cross-repo-analytics/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CodebaseHealthRepoIdRoute = CodebaseHealthRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => CodebaseHealthRoute,
} as any)
const BusFactorAndOwnershipRepoIdRoute =
  BusFactorAndOwnershipRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => BusFactorAndOwnershipRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/risk-analytics': typeof RiskAnalyticsRouteWithChildren
  '/social-network-analysis': typeof SocialNetworkAnalysisRouteWithChildren
  '/technical-debt-indicators': typeof TechnicalDebtIndicatorsRouteWithChildren
  '/bus-factor-and-ownership/$repoId': typeof BusFactorAndOwnershipRepoIdRoute
  '/codebase-health/$repoId': typeof CodebaseHealthRepoIdRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/cross-repo-risk-analytics/$projectId': typeof CrossRepoRiskAnalyticsProjectIdRoute
  '/cross-repo-social-network-analysis/$projectId': typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  '/cross-repo-technical-debt-indicators/$projectId': typeof CrossRepoTechnicalDebtIndicatorsProjectIdRoute
  '/dashboard/$repoId': typeof DashboardRepoIdRoute
  '/developer-analytics/$repoId': typeof DeveloperAnalyticsRepoIdRoute
  '/repository-evolution/$repoId': typeof RepositoryEvolutionRepoIdRoute
  '/risk-analytics/$repoId': typeof RiskAnalyticsRepoIdRoute
  '/social-network-analysis/$repoId': typeof SocialNetworkAnalysisRepoIdRoute
  '/technical-debt-indicators/$repoId': typeof TechnicalDebtIndicatorsRepoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/risk-analytics': typeof RiskAnalyticsRouteWithChildren
  '/social-network-analysis': typeof SocialNetworkAnalysisRouteWithChildren
  '/technical-debt-indicators': typeof TechnicalDebtIndicatorsRouteWithChildren
  '/bus-factor-and-ownership/$repoId': typeof BusFactorAndOwnershipRepoIdRoute
  '/codebase-health/$repoId': typeof CodebaseHealthRepoIdRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/cross-repo-risk-analytics/$projectId': typeof CrossRepoRiskAnalyticsProjectIdRoute
  '/cross-repo-social-network-analysis/$projectId': typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  '/cross-repo-technical-debt-indicators/$projectId': typeof CrossRepoTechnicalDebtIndicatorsProjectIdRoute
  '/dashboard/$repoId': typeof DashboardRepoIdRoute
  '/developer-analytics/$repoId': typeof DeveloperAnalyticsRepoIdRoute
  '/repository-evolution/$repoId': typeof RepositoryEvolutionRepoIdRoute
  '/risk-analytics/$repoId': typeof RiskAnalyticsRepoIdRoute
  '/social-network-analysis/$repoId': typeof SocialNetworkAnalysisRepoIdRoute
  '/technical-debt-indicators/$repoId': typeof TechnicalDebtIndicatorsRepoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus-factor-and-ownership': typeof BusFactorAndOwnershipRouteWithChildren
  '/codebase-health': typeof CodebaseHealthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/developer-analytics': typeof DeveloperAnalyticsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/repository-evolution': typeof RepositoryEvolutionRouteWithChildren
  '/risk-analytics': typeof RiskAnalyticsRouteWithChildren
  '/social-network-analysis': typeof SocialNetworkAnalysisRouteWithChildren
  '/technical-debt-indicators': typeof TechnicalDebtIndicatorsRouteWithChildren
  '/bus-factor-and-ownership/$repoId': typeof BusFactorAndOwnershipRepoIdRoute
  '/codebase-health/$repoId': typeof CodebaseHealthRepoIdRoute
  '/cross-repo-analytics/$projectId': typeof CrossRepoAnalyticsProjectIdRoute
  '/cross-repo-bus-factor-and-ownership/$projectId': typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  '/cross-repo-codebase-health/$projectId': typeof CrossRepoCodebaseHealthProjectIdRoute
  '/cross-repo-repository-evolution/$projectId': typeof CrossRepoRepositoryEvolutionProjectIdRoute
  '/cross-repo-risk-analytics/$projectId': typeof CrossRepoRiskAnalyticsProjectIdRoute
  '/cross-repo-social-network-analysis/$projectId': typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  '/cross-repo-technical-debt-indicators/$projectId': typeof CrossRepoTechnicalDebtIndicatorsProjectIdRoute
  '/dashboard/$repoId': typeof DashboardRepoIdRoute
  '/developer-analytics/$repoId': typeof DeveloperAnalyticsRepoIdRoute
  '/repository-evolution/$repoId': typeof RepositoryEvolutionRepoIdRoute
  '/risk-analytics/$repoId': typeof RiskAnalyticsRepoIdRoute
  '/social-network-analysis/$repoId': typeof SocialNetworkAnalysisRepoIdRoute
  '/technical-debt-indicators/$repoId': typeof TechnicalDebtIndicatorsRepoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/risk-analytics'
    | '/social-network-analysis'
    | '/technical-debt-indicators'
    | '/bus-factor-and-ownership/$repoId'
    | '/codebase-health/$repoId'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/cross-repo-risk-analytics/$projectId'
    | '/cross-repo-social-network-analysis/$projectId'
    | '/cross-repo-technical-debt-indicators/$projectId'
    | '/dashboard/$repoId'
    | '/developer-analytics/$repoId'
    | '/repository-evolution/$repoId'
    | '/risk-analytics/$repoId'
    | '/social-network-analysis/$repoId'
    | '/technical-debt-indicators/$repoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/risk-analytics'
    | '/social-network-analysis'
    | '/technical-debt-indicators'
    | '/bus-factor-and-ownership/$repoId'
    | '/codebase-health/$repoId'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/cross-repo-risk-analytics/$projectId'
    | '/cross-repo-social-network-analysis/$projectId'
    | '/cross-repo-technical-debt-indicators/$projectId'
    | '/dashboard/$repoId'
    | '/developer-analytics/$repoId'
    | '/repository-evolution/$repoId'
    | '/risk-analytics/$repoId'
    | '/social-network-analysis/$repoId'
    | '/technical-debt-indicators/$repoId'
  id:
    | '__root__'
    | '/'
    | '/bus-factor-and-ownership'
    | '/codebase-health'
    | '/dashboard'
    | '/developer-analytics'
    | '/projects'
    | '/repository-evolution'
    | '/risk-analytics'
    | '/social-network-analysis'
    | '/technical-debt-indicators'
    | '/bus-factor-and-ownership/$repoId'
    | '/codebase-health/$repoId'
    | '/cross-repo-analytics/$projectId'
    | '/cross-repo-bus-factor-and-ownership/$projectId'
    | '/cross-repo-codebase-health/$projectId'
    | '/cross-repo-repository-evolution/$projectId'
    | '/cross-repo-risk-analytics/$projectId'
    | '/cross-repo-social-network-analysis/$projectId'
    | '/cross-repo-technical-debt-indicators/$projectId'
    | '/dashboard/$repoId'
    | '/developer-analytics/$repoId'
    | '/repository-evolution/$repoId'
    | '/risk-analytics/$repoId'
    | '/social-network-analysis/$repoId'
    | '/technical-debt-indicators/$repoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusFactorAndOwnershipRoute: typeof BusFactorAndOwnershipRouteWithChildren
  CodebaseHealthRoute: typeof CodebaseHealthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DeveloperAnalyticsRoute: typeof DeveloperAnalyticsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RepositoryEvolutionRoute: typeof RepositoryEvolutionRouteWithChildren
  RiskAnalyticsRoute: typeof RiskAnalyticsRouteWithChildren
  SocialNetworkAnalysisRoute: typeof SocialNetworkAnalysisRouteWithChildren
  TechnicalDebtIndicatorsRoute: typeof TechnicalDebtIndicatorsRouteWithChildren
  CrossRepoAnalyticsProjectIdRoute: typeof CrossRepoAnalyticsProjectIdRoute
  CrossRepoBusFactorAndOwnershipProjectIdRoute: typeof CrossRepoBusFactorAndOwnershipProjectIdRoute
  CrossRepoCodebaseHealthProjectIdRoute: typeof CrossRepoCodebaseHealthProjectIdRoute
  CrossRepoRepositoryEvolutionProjectIdRoute: typeof CrossRepoRepositoryEvolutionProjectIdRoute
  CrossRepoRiskAnalyticsProjectIdRoute: typeof CrossRepoRiskAnalyticsProjectIdRoute
  CrossRepoSocialNetworkAnalysisProjectIdRoute: typeof CrossRepoSocialNetworkAnalysisProjectIdRoute
  CrossRepoTechnicalDebtIndicatorsProjectIdRoute: typeof CrossRepoTechnicalDebtIndicatorsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-debt-indicators': {
      id: '/technical-debt-indicators'
      path: '/technical-debt-indicators'
      fullPath: '/technical-debt-indicators'
      preLoaderRoute: typeof TechnicalDebtIndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-network-analysis': {
      id: '/social-network-analysis'
      path: '/social-network-analysis'
      fullPath: '/social-network-analysis'
      preLoaderRoute: typeof SocialNetworkAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-analytics': {
      id: '/risk-analytics'
      path: '/risk-analytics'
      fullPath: '/risk-analytics'
      preLoaderRoute: typeof RiskAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository-evolution': {
      id: '/repository-evolution'
      path: '/repository-evolution'
      fullPath: '/repository-evolution'
      preLoaderRoute: typeof RepositoryEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-analytics': {
      id: '/developer-analytics'
      path: '/developer-analytics'
      fullPath: '/developer-analytics'
      preLoaderRoute: typeof DeveloperAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase-health': {
      id: '/codebase-health'
      path: '/codebase-health'
      fullPath: '/codebase-health'
      preLoaderRoute: typeof CodebaseHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-factor-and-ownership': {
      id: '/bus-factor-and-ownership'
      path: '/bus-factor-and-ownership'
      fullPath: '/bus-factor-and-ownership'
      preLoaderRoute: typeof BusFactorAndOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-debt-indicators/$repoId': {
      id: '/technical-debt-indicators/$repoId'
      path: '/$repoId'
      fullPath: '/technical-debt-indicators/$repoId'
      preLoaderRoute: typeof TechnicalDebtIndicatorsRepoIdRouteImport
      parentRoute: typeof TechnicalDebtIndicatorsRoute
    }
    '/social-network-analysis/$repoId': {
      id: '/social-network-analysis/$repoId'
      path: '/$repoId'
      fullPath: '/social-network-analysis/$repoId'
      preLoaderRoute: typeof SocialNetworkAnalysisRepoIdRouteImport
      parentRoute: typeof SocialNetworkAnalysisRoute
    }
    '/risk-analytics/$repoId': {
      id: '/risk-analytics/$repoId'
      path: '/$repoId'
      fullPath: '/risk-analytics/$repoId'
      preLoaderRoute: typeof RiskAnalyticsRepoIdRouteImport
      parentRoute: typeof RiskAnalyticsRoute
    }
    '/repository-evolution/$repoId': {
      id: '/repository-evolution/$repoId'
      path: '/$repoId'
      fullPath: '/repository-evolution/$repoId'
      preLoaderRoute: typeof RepositoryEvolutionRepoIdRouteImport
      parentRoute: typeof RepositoryEvolutionRoute
    }
    '/developer-analytics/$repoId': {
      id: '/developer-analytics/$repoId'
      path: '/$repoId'
      fullPath: '/developer-analytics/$repoId'
      preLoaderRoute: typeof DeveloperAnalyticsRepoIdRouteImport
      parentRoute: typeof DeveloperAnalyticsRoute
    }
    '/dashboard/$repoId': {
      id: '/dashboard/$repoId'
      path: '/$repoId'
      fullPath: '/dashboard/$repoId'
      preLoaderRoute: typeof DashboardRepoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/cross-repo-technical-debt-indicators/$projectId': {
      id: '/cross-repo-technical-debt-indicators/$projectId'
      path: '/cross-repo-technical-debt-indicators/$projectId'
      fullPath: '/cross-repo-technical-debt-indicators/$projectId'
      preLoaderRoute: typeof CrossRepoTechnicalDebtIndicatorsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-social-network-analysis/$projectId': {
      id: '/cross-repo-social-network-analysis/$projectId'
      path: '/cross-repo-social-network-analysis/$projectId'
      fullPath: '/cross-repo-social-network-analysis/$projectId'
      preLoaderRoute: typeof CrossRepoSocialNetworkAnalysisProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-risk-analytics/$projectId': {
      id: '/cross-repo-risk-analytics/$projectId'
      path: '/cross-repo-risk-analytics/$projectId'
      fullPath: '/cross-repo-risk-analytics/$projectId'
      preLoaderRoute: typeof CrossRepoRiskAnalyticsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-repository-evolution/$projectId': {
      id: '/cross-repo-repository-evolution/$projectId'
      path: '/cross-repo-repository-evolution/$projectId'
      fullPath: '/cross-repo-repository-evolution/$projectId'
      preLoaderRoute: typeof CrossRepoRepositoryEvolutionProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-codebase-health/$projectId': {
      id: '/cross-repo-codebase-health/$projectId'
      path: '/cross-repo-codebase-health/$projectId'
      fullPath: '/cross-repo-codebase-health/$projectId'
      preLoaderRoute: typeof CrossRepoCodebaseHealthProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-bus-factor-and-ownership/$projectId': {
      id: '/cross-repo-bus-factor-and-ownership/$projectId'
      path: '/cross-repo-bus-factor-and-ownership/$projectId'
      fullPath: '/cross-repo-bus-factor-and-ownership/$projectId'
      preLoaderRoute: typeof CrossRepoBusFactorAndOwnershipProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-repo-analytics/$projectId': {
      id: '/cross-repo-analytics/$projectId'
      path: '/cross-repo-analytics/$projectId'
      fullPath: '/cross-repo-analytics/$projectId'
      preLoaderRoute: typeof CrossRepoAnalyticsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase-health/$repoId': {
      id: '/codebase-health/$repoId'
      path: '/$repoId'
      fullPath: '/codebase-health/$repoId'
      preLoaderRoute: typeof CodebaseHealthRepoIdRouteImport
      parentRoute: typeof CodebaseHealthRoute
    }
    '/bus-factor-and-ownership/$repoId': {
      id: '/bus-factor-and-ownership/$repoId'
      path: '/$repoId'
      fullPath: '/bus-factor-and-ownership/$repoId'
      preLoaderRoute: typeof BusFactorAndOwnershipRepoIdRouteImport
      parentRoute: typeof BusFactorAndOwnershipRoute
    }
  }
}

interface BusFactorAndOwnershipRouteChildren {
  BusFactorAndOwnershipRepoIdRoute: typeof BusFactorAndOwnershipRepoIdRoute
}

const BusFactorAndOwnershipRouteChildren: BusFactorAndOwnershipRouteChildren = {
  BusFactorAndOwnershipRepoIdRoute: BusFactorAndOwnershipRepoIdRoute,
}

const BusFactorAndOwnershipRouteWithChildren =
  BusFactorAndOwnershipRoute._addFileChildren(
    BusFactorAndOwnershipRouteChildren,
  )

interface CodebaseHealthRouteChildren {
  CodebaseHealthRepoIdRoute: typeof CodebaseHealthRepoIdRoute
}

const CodebaseHealthRouteChildren: CodebaseHealthRouteChildren = {
  CodebaseHealthRepoIdRoute: CodebaseHealthRepoIdRoute,
}

const CodebaseHealthRouteWithChildren = CodebaseHealthRoute._addFileChildren(
  CodebaseHealthRouteChildren,
)

interface DashboardRouteChildren {
  DashboardRepoIdRoute: typeof DashboardRepoIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRepoIdRoute: DashboardRepoIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeveloperAnalyticsRouteChildren {
  DeveloperAnalyticsRepoIdRoute: typeof DeveloperAnalyticsRepoIdRoute
}

const DeveloperAnalyticsRouteChildren: DeveloperAnalyticsRouteChildren = {
  DeveloperAnalyticsRepoIdRoute: DeveloperAnalyticsRepoIdRoute,
}

const DeveloperAnalyticsRouteWithChildren =
  DeveloperAnalyticsRoute._addFileChildren(DeveloperAnalyticsRouteChildren)

interface RepositoryEvolutionRouteChildren {
  RepositoryEvolutionRepoIdRoute: typeof RepositoryEvolutionRepoIdRoute
}

const RepositoryEvolutionRouteChildren: RepositoryEvolutionRouteChildren = {
  RepositoryEvolutionRepoIdRoute: RepositoryEvolutionRepoIdRoute,
}

const RepositoryEvolutionRouteWithChildren =
  RepositoryEvolutionRoute._addFileChildren(RepositoryEvolutionRouteChildren)

interface RiskAnalyticsRouteChildren {
  RiskAnalyticsRepoIdRoute: typeof RiskAnalyticsRepoIdRoute
}

const RiskAnalyticsRouteChildren: RiskAnalyticsRouteChildren = {
  RiskAnalyticsRepoIdRoute: RiskAnalyticsRepoIdRoute,
}

const RiskAnalyticsRouteWithChildren = RiskAnalyticsRoute._addFileChildren(
  RiskAnalyticsRouteChildren,
)

interface SocialNetworkAnalysisRouteChildren {
  SocialNetworkAnalysisRepoIdRoute: typeof SocialNetworkAnalysisRepoIdRoute
}

const SocialNetworkAnalysisRouteChildren: SocialNetworkAnalysisRouteChildren = {
  SocialNetworkAnalysisRepoIdRoute: SocialNetworkAnalysisRepoIdRoute,
}

const SocialNetworkAnalysisRouteWithChildren =
  SocialNetworkAnalysisRoute._addFileChildren(
    SocialNetworkAnalysisRouteChildren,
  )

interface TechnicalDebtIndicatorsRouteChildren {
  TechnicalDebtIndicatorsRepoIdRoute: typeof TechnicalDebtIndicatorsRepoIdRoute
}

const TechnicalDebtIndicatorsRouteChildren: TechnicalDebtIndicatorsRouteChildren =
  {
    TechnicalDebtIndicatorsRepoIdRoute: TechnicalDebtIndicatorsRepoIdRoute,
  }

const TechnicalDebtIndicatorsRouteWithChildren =
  TechnicalDebtIndicatorsRoute._addFileChildren(
    TechnicalDebtIndicatorsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusFactorAndOwnershipRoute: BusFactorAndOwnershipRouteWithChildren,
  CodebaseHealthRoute: CodebaseHealthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DeveloperAnalyticsRoute: DeveloperAnalyticsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RepositoryEvolutionRoute: RepositoryEvolutionRouteWithChildren,
  RiskAnalyticsRoute: RiskAnalyticsRouteWithChildren,
  SocialNetworkAnalysisRoute: SocialNetworkAnalysisRouteWithChildren,
  TechnicalDebtIndicatorsRoute: TechnicalDebtIndicatorsRouteWithChildren,
  CrossRepoAnalyticsProjectIdRoute: CrossRepoAnalyticsProjectIdRoute,
  CrossRepoBusFactorAndOwnershipProjectIdRoute:
    CrossRepoBusFactorAndOwnershipProjectIdRoute,
  CrossRepoCodebaseHealthProjectIdRoute: CrossRepoCodebaseHealthProjectIdRoute,
  CrossRepoRepositoryEvolutionProjectIdRoute:
    CrossRepoRepositoryEvolutionProjectIdRoute,
  CrossRepoRiskAnalyticsProjectIdRoute: CrossRepoRiskAnalyticsProjectIdRoute,
  CrossRepoSocialNetworkAnalysisProjectIdRoute:
    CrossRepoSocialNetworkAnalysisProjectIdRoute,
  CrossRepoTechnicalDebtIndicatorsProjectIdRoute:
    CrossRepoTechnicalDebtIndicatorsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
