name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: write-all
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm run install:all

      - name: Check code formatting
        run: npm run format:check

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build
      - name: Generate Backend Test Coverage
        working-directory: server
        run: npm run test:coverage

      - name: Generate Frontend Test Coverage
        working-directory: client
        run: npm run test:coverage

      - name: Upload Backend Test Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: server/coverage/
          retention-days: 7

      - name: Upload Frontend Test Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: client/coverage/
          retention-days: 7

      # Report code coverage as a comment on pull requests
      - name: Report Backend Test Coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./server/coverage/lcov.info

      - name: Report Frontend Test Coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./client/coverage/lcov.info
